name: CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master, ci ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetos: linux
            targetarch: amd64
          - os: ubuntu-latest
            targetos: linux
            targetarch: i386
          - os: ubuntu-latest-arm
            targetos: linux
            targetarch: arm64
          - os: ubuntu-latest-arm
            targetos: linux
            targetarch: armhf

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: jetbrains
        java-version: 25

    - name: Install dependencies
      run: bash ci/deps_${{ matrix.targetos }}.sh

    - name: Build artifacts
      run: mkdir build && cd build && cmake .. && make

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.targetos }}-${{ matrix.targetarch }}_libusb4java.so
        path: build/src/libusb4java.so
