name: CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master, ci ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      EXTENSION: "so"
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
#         - os: ubuntu-latest
#           targetos: linux
#           targetarch: amd64
#         - os: ubuntu-latest
#           targetos: linux
#           targetarch: i386
#         - os: ubuntu-24.04-arm
#           targetos: linux
#           targetarch: arm64
#         - os: ubuntu-24.04-arm
#           targetos: linux
#           targetarch: armhf
#         - os: macos-14
#           targetos: apple
#           targetarch: arm64
#         - os: macos-15-intel
#           targetos: apple
#           targetarch: amd64
          - os: windows-latest
            targetos: win32
            targetarch: amd64
#         - os: windows-2022
#           targetos: win32
#           targetarch: i386

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: jetbrains
        java-version: 25

    - name: Install dependencies
      run: bash ci/deps_${{ matrix.targetos }}.sh

    - name: Build artifacts
      run: mkdir build && cd build && cmake .. && cmake --build . --config Release

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.targetos }}-${{ matrix.targetarch }}_libusb4java.${{ env.EXTENSION }}
        path: build/src/Release/*usb4java.${{ env.EXTENSION }}
